### PR TITLE
Aaap.

### PR DESCRIPTION
**Pull request by Elektr0X**
### Short Description
changes: 
cradlized, parallel, concurrent, extraUnitTests, serialised, immutablised, timing, test coverage ... polymorphized 
p.s. thanks for the API ... 

### Issue Reference
fixes #

### Checks

- [ ] This PR follows the coding guidelines of the project
- [ ] This PR fulfills the acceptance criteria defined on the issue
- [ ] This PR has been locally tested
- [ ] Changes in this PR are unit tested

### CODE REVIEW

**Comment by aaap03** [comment]
@robertblust

**Comment by gabac** [comment]
@aaap03 We are a bit unsure who you are as you also created a new GitHub account. Would mind dropping us a mail?

**Comment by aaap03** [comment]
I'm asking just a review for my code from @robertblust **if it possible**  :-)

**Comment by robertblust** [comment]
@aaap03 I spend some time and browsed your code. A lot of refactoring.

As the repository purpose explains. This is a small development exercise which is part of our talent recruitment process. The exercise is a real tasks which a 3ap developer could face. We develop digital solutions for our client in an agile way. We focus on providing business value for our client and the code should be maintainable.

Introducing Gradle and the whole refactoring you did is not part of the exercise. Imagine, that this is a project we develop for a client. How you convince the client that your effort for introducing Gradle and the whole refactoring was required in favor of maybe some other things we could not do? 

And why you created a github user which has our company name in it 🤔 ? Do you want to hide your identity? A Github account provides a lot of insights. In which public repo you participating? Which repo you forked. This are things we as well take a look in our talent recruiting process.

So summarized. This PR makes me thinking:
- Who you are?
- Why you hide your real identity?
- What you like to show me? Cause the PR is not what the exercise request 🤔

**Comment by NandX00r** [comment]
me? external from 3ap worked in my company and told me about the assignment and how geek you are and I decided to solve it. API is high level.

**Pull request closed without merging**
